// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQtJiFSeQWkjx7IKXiqEqHwsPMxZQ49NQ',
    appId: '1:301481817685:web:77c1d2339a1bccc93a46dc',
    messagingSenderId: '301481817685',
    projectId: 'penilaian-pegawai-b1db3',
    authDomain: 'penilaian-pegawai-b1db3.firebaseapp.com',
    storageBucket: 'penilaian-pegawai-b1db3.firebasestorage.app',
    measurementId: 'G-EGLMJMBV64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDriEMtvSNM6uzeA1wKJzMhl5IAFopa3CM',
    appId: '1:301481817685:android:35504b0ce95925743a46dc',
    messagingSenderId: '301481817685',
    projectId: 'penilaian-pegawai-b1db3',
    storageBucket: 'penilaian-pegawai-b1db3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3JY-b478sEt0dI4Rnkd2I0z-mZI2sUMY',
    appId: '1:301481817685:ios:56ba08b2af83af243a46dc',
    messagingSenderId: '301481817685',
    projectId: 'penilaian-pegawai-b1db3',
    storageBucket: 'penilaian-pegawai-b1db3.firebasestorage.app',
    iosBundleId: 'com.dpmptsp.penilaianpegawai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3JY-b478sEt0dI4Rnkd2I0z-mZI2sUMY',
    appId: '1:301481817685:ios:93aff0155b0d6d473a46dc',
    messagingSenderId: '301481817685',
    projectId: 'penilaian-pegawai-b1db3',
    storageBucket: 'penilaian-pegawai-b1db3.firebasestorage.app',
    iosBundleId: 'com.example.projectPkl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQtJiFSeQWkjx7IKXiqEqHwsPMxZQ49NQ',
    appId: '1:301481817685:web:fdea9e3b6df9c3e23a46dc',
    messagingSenderId: '301481817685',
    projectId: 'penilaian-pegawai-b1db3',
    authDomain: 'penilaian-pegawai-b1db3.firebaseapp.com',
    storageBucket: 'penilaian-pegawai-b1db3.firebasestorage.app',
    measurementId: 'G-QVRBCGR541',
  );
}
